Repository hmcts/darts-gateway, pull requests merged in 2024-10, with the labels that each got.

#555 Update application.yaml
  src/main/resources/application.yaml
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-555

#558 Create CODEOWNERS
  CODEOWNERS
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-558

#556 Update CODEOWNERS
  .github/CODEOWNERS
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-556

#562 Try this @Jack
  CODEOWNERS
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-562

#563 This one needs changing too @Jack
  .github/CODEOWNERS
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-563

#566 Exclude performance test from main functional test execution
  build.gradle
  src/functionalTest/README.md
  src/functionalTest/java/uk/gov/hmcts/darts/FunctionalTestBase.java
  src/functionalTest/java/uk/gov/hmcts/darts/performance/ContextRegistryPerformanceTest.java
  src/functionalTest/java/uk/gov/hmcts/darts/performance/FunctionalPerformanceTestBase.java
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-566

#577 Dependency update
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/darts/testutils/MemoryLogAppender.java
  src/main/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptor.java
  src/main/java/uk/gov/hmcts/darts/cache/token/component/impl/TokenValidatorImpl.java
  src/main/java/uk/gov/hmcts/darts/log/conf/LogProperties.java
  src/test/java/uk/gov/hmcts/darts/log/service/impl/DarNotificationLoggerServiceImplTest.java
  src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/ctxt/ContextRegistryClientProvider.java
  src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/ctxt/ContextRegistryXmlClient.java
  src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/darts/DartsGatewayMtomClient.java
  src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/darts/DartsGatewayXmlClient.java
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-577

#600 add postman collection
  DARTS-Gateway.postman_collection.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-600
