Repository hmcts/darts-gateway, pull requests merged in 2025-05, with the labels that each got.

#777 DMP-5095 Fixing DAR notify log message date time
  src/integrationTest/java/uk/gov/hmcts/darts/event/controller/DarNotifyControllerTest.java
  src/main/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClient.java
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-777

#775 DMP-5055 Move from Jitpack to Azure Devops Artifacts
  README.md
  build.gradle
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-775

#778 DMP-5055 Always use the latest release of darts-api openapi specs
  build.gradle
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-778

#779 Update group name
  build.gradle
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-779

#792 Temporarily disable automerge of Renovate
  .github/renovate.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-gateway-pr-792
